server:
  port: 8821

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
  application:
    name: rbac-provider-server
  # 数据源配置
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/chengfeng?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

    # Druid连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化
    initialSize: 3
    # 最大
    maxActive: 20
    # 最小
    minIdle: 3
    # 最大连接等待超时时间
    maxWait: 60000
    # 打开PSCache,并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间,单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置监控统计拦截的filters,去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
  # spring data jpa配置
  jpa:
    hibernate:
      # 实体类有更新时，数据库表更新
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  http:
    # 过滤字符编码
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

core.security.shiro:
  casServerUrlPrefix: http://localhost/bscsso
  casValidatorUrl: http://localhost/bscsso
  casService: http://localhost:8821/cas
  successUrl: http://localhost:8821/ui/frontend/login
  filterChainDefinitionMap:
    /static/**: anon
    /api/**: anon
    /cas: cas
    /nmis/**: anon

spring.thymeleaf:
  cache: false
#文件保存前缀
tom.files.path: D:/fcFiles/
